name: Update FTP Folder Structure

on:
  schedule:
    # Runs every 10 minutes (UTC)
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update_structure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lftp
        pip install --upgrade pip

    - name: Fetch FTP folder structure using ls -R
      env:
        FTP_SERVER: "ftp.ebi.ac.uk"  # Replace with your FTP server if needed
        FTP_PATH: "/pub/ensemblorganisms"  # Replace with desired FTP path
      run: |
        lftp -c "open $FTP_SERVER; cd $FTP_PATH; ls -R" > tree_lsR.txt

    - name: Convert structure to JSON
      run: |
        python3 << 'EOF'
        import json

        def parse_ls_output(file_path):
            tree = {}
            current_path = []  # Current directory path (list)
            
            with open(file_path, "r") as f:
                for line in f:
                    line = line.rstrip("\n")
                    if not line:
                        continue
                    # Directory header (lines ending with ':')
                    if line.endswith(":"):
                        header = line[:-1]
                        # If header is the root, set current_path to empty list
                        if header == ".":
                            current_path = []
                        else:
                            # Remove the "./" prefix if present, then split path by "/"
                            if header.startswith("./"):
                                header = header[2:]
                            current_path = header.split("/")
                        continue
                    
                    # The ls output is in the format: permissions, link count, owner, group, size, date, time, filename.
                    # Since filenames may contain spaces, join fields from the 9th element onward.
                    parts = line.split()
                    if len(parts) < 9:
                        continue  # Skip unexpected format lines
                    filename = " ".join(parts[8:])
                    # If the first field starts with 'd', it is a directory.
                    is_dir = parts[0].startswith("d")
                    
                    # Navigate through the tree based on the current path.
                    node = tree
                    for part in current_path:
                        node = node.setdefault(part, {})
                    # Add the file or directory entry.
                    if is_dir:
                        node[filename] = {}
                    else:
                        node[filename] = None
            return tree

        if __name__ == "__main__":
            input_file = "ensembl-beta_ftp_structure.txt"  # File generated by lftp
            output_file = "ensembl-beta_ftp_structure.json"
            
            directory_tree = parse_ls_output(input_file)
            
            with open(output_file, "w") as out_f:
                json.dump(directory_tree, out_f, indent=4)
            
            print(f"Directory structure saved to {output_file}.")
        EOF

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        if [ -n "$(git status --porcelain ensembl-beta_ftp_structure.json)" ]; then
          git add ensembl-beta_ftp_structure.txt ensembl-beta_ftp_structure.json
          git commit -m "Update FTP folder structure"
          git push
        else
          echo "No changes to commit."
        fi
