name: Update FTP Folder Structure

on:
  schedule:
    # Runs every 10 minutes (UTC)
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  update_structure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lftp
        pip install --upgrade pip

    - name: Fetch FTP folder structure
      env:
        FTP_SERVER: "ftp.ensembl.org"  # Replace with your FTP server address if needed
        FTP_PATH: "/pub"               # Replace with the desired path
      run: |
        lftp -c "open $FTP_SERVER; find $FTP_PATH" > ensembl-beta_ftp_structure.txt

    - name: Convert structure to JSON
      run: |
        python3 << 'EOF'
        import json

        def parse_ls_output(file_path):
            # Initialize an empty dictionary to hold the directory tree
            tree = {}
            # List to hold the current directory path components
            current_path = []
            
            with open(file_path, "r") as f:
                for line in f:
                    line = line.rstrip("\n")
                    if not line:
                        continue
                    # Check if the line is a directory header (ends with ":")
                    if line.endswith(":"):
                        header = line[:-1]
                        # If the header is the root (".") set current_path to an empty list
                        if header == ".":
                            current_path = []
                        else:
                            # Remove the "./" prefix if present, then split the path by "/"
                            if header.startswith("./"):
                                header = header[2:]
                            current_path = header.split("/")
                        continue
                    
                    # The lftp ls output format is: permissions, link count, owner, group, size, date, time, filename.
                    # Since filenames may contain spaces, join the parts from the 9th field onward.
                    parts = line.split()
                    if len(parts) < 9:
                        continue  # Skip unexpected format lines
                    filename = " ".join(parts[8:])
                    # Determine if the entry is a directory (permissions field starts with "d")
                    is_dir = parts[0].startswith("d")
                    
                    # Navigate through the tree based on the current path
                    node = tree
                    for part in current_path:
                        node = node.setdefault(part, {})
                    # Add the file or directory entry to the current node
                    if is_dir:
                        node[filename] = {}
                    else:
                        node[filename] = None
            return tree

        if __name__ == "__main__":
            input_file = "ensembl-beta_ftp_structure.txt"  # File generated by lftp
            output_file = "ensembl-beta_ftp_structure.json"
            
            directory_tree = parse_ls_output(input_file)
            
            with open(output_file, "w") as out_f:
                json.dump(directory_tree, out_f, indent=4)
            
            print(f"Directory structure saved to {output_file}.")
        EOF

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        # Commit only if there are changes in the JSON file
        if [ -n "$(git status --porcelain tree_lsR.json)" ]; then
          git add ensembl-beta_ftp_structure.json
          git commit -m "Update FTP folder structure"
          git push
        else
          echo "No changes to commit."
        fi